spring.application.name=cinema
spring.profiles.active=develop

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=cine
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.pathmatch.use-suffix-pattern=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method