spring.datasource.url=jdbc:postgresql://localhost:5433/cine_db
spring.datasource.username=cine_user
spring.datasource.password=cine_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
